project:
  type: book

book:
  title: "STAT 468 Final Project - Tennis Prediction"
  author: "CZ Fu"
  chapters:
    - index.qmd
    - 01-question.qmd
    - 02-import.qmd
    - 03-tidy.qmd
    - 04-transform.qmd
    - 05-visualize.qmd
    - 06-model.qmd
    - 07-communicate.qmd
  page-navigation: true

format:
  html:
    toc: true
    code-fold: true

execute:
  eval: false
  warning: false
  message: false
